### ISSUE TITLE
Research MEAN stack

### ISSUE THREAD

**Issue by JasonKraft** [Candeles/doctormarkdown#38]
## Done Conditions

- A good understanding of how to use Mongo in Node
- A good understanding of how to use Express in Node
  - A good understanding of the MVC paradigm
- A good understanding of how to use Angular
- Find and complete a good tutorial for the MEAN stack
- Read up on Sockets.io

**Comment by LimitedWard** [comment]
[A good video for reference](https://www.youtube.com/watch?v=rlVwJvE3C5A&list=PL6rhBJX0L3TWYrwrQIi1_MzQDvVhkUVPI)
